/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package info5100;

import info5100.Beans.Car;
import info5100.Beans.ServiceRecord;
import info5100.UI.FileDialog;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import com.google.gson.Gson;
import info5100.Utils.Verifier;
import java.awt.Component;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Date;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class container extends javax.swing.JFrame {

    /**
     * Creates new form container
     */
    public int added = 0;
    public ServiceRecord sr;
    public ArrayList<ServiceRecord> list = new ArrayList<>();
    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    public container() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        car = new info5100.Beans.Car();
        cardPanel = new javax.swing.JPanel();
        card1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        telephoneNumberLabel = new javax.swing.JLabel();
        emailAddressesLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        socialSecurityNumberTextField = new javax.swing.JTextField();
        emailAddressesTextField = new javax.swing.JTextField();
        telephoneNumberTextField = new javax.swing.JTextField();
        driverLicenseLabel = new javax.swing.JLabel();
        modelTextField = new javax.swing.JTextField();
        socialSecurityNumberLabel = new javax.swing.JLabel();
        seatsNumberLabel = new javax.swing.JLabel();
        driverLicenseTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        engineNoTextField = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();
        seatsNumberTextField = new javax.swing.JTextField();
        licensePlatesLabel = new javax.swing.JLabel();
        warrantyYearLabel = new javax.swing.JLabel();
        licensePlatesTextField = new javax.swing.JTextField();
        warrantyYearTextField = new javax.swing.JTextField();
        photoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        brandLabel = new javax.swing.JLabel();
        brandTextField = new javax.swing.JTextField();
        modelLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        engineNoLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        colorTextField = new javax.swing.JTextField();
        photoTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        mileageLabel = new javax.swing.JLabel();
        mileageTextField = new javax.swing.JTextField();
        costTextField = new javax.swing.JTextField();
        companyTextField = new javax.swing.JTextField();
        costLabel = new javax.swing.JLabel();
        companyLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        descriptionTextarea = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        addButton = new javax.swing.JButton();
        showCountLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        dateTextField = new com.toedter.calendar.JDateChooser();
        card2 = new javax.swing.JPanel();
        info = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        nameTextField1 = new javax.swing.JTextField();
        telephoneNumberLabel1 = new javax.swing.JLabel();
        emailAddressesLabel1 = new javax.swing.JLabel();
        addressLabel1 = new javax.swing.JLabel();
        socialSecurityNumberTextField1 = new javax.swing.JTextField();
        emailAddressesTextField1 = new javax.swing.JTextField();
        telephoneNumberTextField1 = new javax.swing.JTextField();
        driverLicenseLabel1 = new javax.swing.JLabel();
        modelTextField1 = new javax.swing.JTextField();
        socialSecurityNumberLabel1 = new javax.swing.JLabel();
        seatsNumberLabel1 = new javax.swing.JLabel();
        driverLicenseTextField1 = new javax.swing.JTextField();
        yearTextField1 = new javax.swing.JTextField();
        addressTextField1 = new javax.swing.JTextField();
        engineNoTextField1 = new javax.swing.JTextField();
        seatsNumberTextField1 = new javax.swing.JTextField();
        licensePlateLabel1 = new javax.swing.JLabel();
        warrantyLabel1 = new javax.swing.JLabel();
        licensePlatesTextField1 = new javax.swing.JTextField();
        warrantyYearTextField1 = new javax.swing.JTextField();
        photoLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        brandLabel1 = new javax.swing.JLabel();
        brandTextField1 = new javax.swing.JTextField();
        modelLabel1 = new javax.swing.JLabel();
        yearLabel1 = new javax.swing.JLabel();
        engineNoLabel1 = new javax.swing.JLabel();
        colorLabel1 = new javax.swing.JLabel();
        colorTextField1 = new javax.swing.JTextField();
        showPhotoLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        serviceRecordTable = new javax.swing.JTable();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(700, 765));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new java.awt.FlowLayout());

        cardPanel.setPreferredSize(new java.awt.Dimension(677, 1050));
        cardPanel.setLayout(new java.awt.CardLayout());

        card1.setPreferredSize(new java.awt.Dimension(672, 650));

        jLabel10.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Owner Information");

        nameLabel.setLabelFor(nameTextField);
        nameLabel.setText("Name");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        telephoneNumberLabel.setLabelFor(telephoneNumberTextField);
        telephoneNumberLabel.setText("TelePhone Number");

        emailAddressesLabel.setLabelFor(emailAddressesTextField);
        emailAddressesLabel.setText("Email Addresses");

        addressLabel.setLabelFor(addressTextField);
        addressLabel.setText("Address");

        socialSecurityNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialSecurityNumberTextFieldActionPerformed(evt);
            }
        });

        telephoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneNumberTextFieldActionPerformed(evt);
            }
        });

        driverLicenseLabel.setLabelFor(driverLicenseTextField);
        driverLicenseLabel.setText("Driver License");

        socialSecurityNumberLabel.setLabelFor(socialSecurityNumberTextField);
        socialSecurityNumberLabel.setText("Social Security Number");

        seatsNumberLabel.setLabelFor(seatsNumberTextField);
        seatsNumberLabel.setText("Seats Number");

        driverLicenseTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverLicenseTextFieldActionPerformed(evt);
            }
        });

        engineNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineNoTextFieldActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        seatsNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsNumberTextFieldActionPerformed(evt);
            }
        });

        licensePlatesLabel.setLabelFor(licensePlatesTextField);
        licensePlatesLabel.setText("License Plates");

        warrantyYearLabel.setLabelFor(warrantyYearTextField);
        warrantyYearLabel.setText("Warranty Year");

        photoLabel.setLabelFor(photoTextField);
        photoLabel.setText("Photo");

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Basic Information");

        brandLabel.setLabelFor(brandTextField);
        brandLabel.setText("Brand");

        brandTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandTextFieldActionPerformed(evt);
            }
        });

        modelLabel.setLabelFor(modelTextField);
        modelLabel.setText("Model");

        yearLabel.setLabelFor(yearTextField);
        yearLabel.setText("Year");

        engineNoLabel.setLabelFor(engineNoTextField);
        engineNoLabel.setText("Engine No");

        colorLabel.setLabelFor(colorTextField);
        colorLabel.setText("Color");

        photoTextField.setEditable(false);

        jButton1.setText("File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Service Record");

        DateLabel.setText("Date");

        mileageLabel.setLabelFor(mileageTextField);
        mileageLabel.setText("Mileage");

        mileageTextField.setEditable(false);

        costTextField.setEditable(false);
        costTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costTextFieldActionPerformed(evt);
            }
        });

        companyTextField.setEditable(false);

        costLabel.setLabelFor(costTextField);
        costLabel.setText("Cost");

        companyLabel.setLabelFor(companyTextField);
        companyLabel.setText("Company");

        descriptionLabel.setText("Description");

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        descriptionTextarea.setViewportView(descriptionTextArea);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        showCountLabel.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        showCountLabel.setText("Added service record count: 0");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        dateTextField.setDateFormatString("yyyy-MM-dd");
        dateTextField.setEnabled(false);

        javax.swing.GroupLayout card1Layout = new javax.swing.GroupLayout(card1);
        card1.setLayout(card1Layout);
        card1Layout.setHorizontalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1Layout.createSequentialGroup()
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(card1Layout.createSequentialGroup()
                                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(modelLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yearLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(engineNoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(licensePlatesLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(photoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(brandLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(modelTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, card1Layout.createSequentialGroup()
                                        .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(licensePlatesTextField)
                                            .addComponent(engineNoTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(yearTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(warrantyYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(colorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seatsNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(colorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                            .addComponent(seatsNumberTextField)
                                            .addComponent(warrantyYearTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(card1Layout.createSequentialGroup()
                                        .addComponent(photoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(brandTextField)))
                            .addGroup(card1Layout.createSequentialGroup()
                                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel)
                                    .addComponent(addressLabel)
                                    .addComponent(emailAddressesLabel)
                                    .addComponent(telephoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTextField)
                                    .addGroup(card1Layout.createSequentialGroup()
                                        .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(telephoneNumberTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailAddressesTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(card1Layout.createSequentialGroup()
                                                .addComponent(socialSecurityNumberLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(socialSecurityNumberTextField))
                                            .addGroup(card1Layout.createSequentialGroup()
                                                .addComponent(driverLicenseLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(driverLicenseTextField))))
                                    .addComponent(addressTextField)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(card1Layout.createSequentialGroup()
                                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(card1Layout.createSequentialGroup()
                                        .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DateLabel)
                                            .addComponent(companyLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(companyTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                            .addComponent(dateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(card1Layout.createSequentialGroup()
                                        .addComponent(addButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saveButton))
                                    .addComponent(showCountLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(card1Layout.createSequentialGroup()
                                        .addComponent(descriptionLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(descriptionTextarea))
                                    .addGroup(card1Layout.createSequentialGroup()
                                        .addComponent(mileageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mileageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(costLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(costTextField))))))
                    .addGroup(card1Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(nextButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        card1Layout.setVerticalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLabel)
                    .addComponent(brandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(colorLabel)
                    .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(engineNoLabel)
                    .addComponent(seatsNumberLabel)
                    .addComponent(engineNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatsNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licensePlatesLabel)
                    .addComponent(warrantyYearLabel)
                    .addComponent(licensePlatesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warrantyYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(photoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneNumberLabel)
                    .addComponent(telephoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driverLicenseLabel)
                    .addComponent(driverLicenseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailAddressesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAddressesLabel)
                    .addComponent(socialSecurityNumberLabel)
                    .addComponent(socialSecurityNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card1Layout.createSequentialGroup()
                        .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DateLabel)
                            .addComponent(mileageLabel)
                            .addComponent(mileageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(card1Layout.createSequentialGroup()
                                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(companyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(companyLabel)
                                    .addComponent(descriptionLabel))
                                .addGap(18, 18, 18)
                                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addButton)
                                    .addComponent(saveButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(showCountLabel))
                            .addComponent(descriptionTextarea, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nextButton))
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(494, Short.MAX_VALUE))
        );

        cardPanel.add(card1, "card1");

        card2.setPreferredSize(new java.awt.Dimension(677, 850));

        info.setPreferredSize(new java.awt.Dimension(665, 830));

        jPanel1.setPreferredSize(new java.awt.Dimension(658, 750));

        jLabel11.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Owner Information");

        nameLabel1.setText("Name");

        nameTextField1.setEditable(false);
        nameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextField1ActionPerformed(evt);
            }
        });

        telephoneNumberLabel1.setText("TelePhone Number");

        emailAddressesLabel1.setText("Email Addresses");

        addressLabel1.setText("Address");

        socialSecurityNumberTextField1.setEditable(false);

        emailAddressesTextField1.setEditable(false);

        telephoneNumberTextField1.setEditable(false);

        driverLicenseLabel1.setText("Driver License");

        modelTextField1.setEditable(false);

        socialSecurityNumberLabel1.setText("Social Security Number");

        seatsNumberLabel1.setText("Seats Number");

        driverLicenseTextField1.setEditable(false);
        driverLicenseTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverLicenseTextField1ActionPerformed(evt);
            }
        });

        yearTextField1.setEditable(false);

        addressTextField1.setEditable(false);

        engineNoTextField1.setEditable(false);

        seatsNumberTextField1.setEditable(false);

        licensePlateLabel1.setText("License Plates");

        warrantyLabel1.setText("Warranty Year");

        licensePlatesTextField1.setEditable(false);

        warrantyYearTextField1.setEditable(false);

        photoLabel1.setText("Photo");

        jLabel2.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Basic Information");

        brandLabel1.setText("Brand");

        brandTextField1.setEditable(false);
        brandTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandTextField1ActionPerformed(evt);
            }
        });

        modelLabel1.setText("Model");

        yearLabel1.setText("Year");

        engineNoLabel1.setText("Engine No");

        colorLabel1.setText("Color");

        colorTextField1.setEditable(false);

        javax.swing.ImageIcon icon;

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(photoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showPhotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(105, 105, 105))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel1)
                                    .addComponent(addressLabel1)
                                    .addComponent(emailAddressesLabel1)
                                    .addComponent(telephoneNumberLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTextField1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(telephoneNumberTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailAddressesTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(socialSecurityNumberLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(socialSecurityNumberTextField1))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(driverLicenseLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(driverLicenseTextField1))))
                                    .addComponent(addressTextField1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(brandLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(modelLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yearLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(engineNoLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(licensePlateLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(yearTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                            .addComponent(engineNoTextField1)
                                            .addComponent(licensePlatesTextField1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(warrantyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(colorLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seatsNumberLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(colorTextField1)
                                            .addComponent(seatsNumberTextField1)
                                            .addComponent(warrantyYearTextField1, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(brandTextField1)
                                        .addGap(74, 74, 74))
                                    .addComponent(modelTextField1))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(107, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLabel1)
                    .addComponent(brandTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel1)
                    .addComponent(colorLabel1)
                    .addComponent(colorTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(engineNoLabel1)
                    .addComponent(seatsNumberLabel1)
                    .addComponent(engineNoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatsNumberTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licensePlateLabel1)
                    .addComponent(warrantyLabel1)
                    .addComponent(licensePlatesTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warrantyYearTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photoLabel1)
                    .addComponent(showPhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneNumberLabel1)
                    .addComponent(telephoneNumberTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driverLicenseLabel1)
                    .addComponent(driverLicenseTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailAddressesTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAddressesLabel1)
                    .addComponent(socialSecurityNumberLabel1)
                    .addComponent(socialSecurityNumberTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel1))
                .addGap(55, 55, 55))
        );

        //try {
            //ShowImage si = new ShowImage();
            //    icon = si.getImage();
            //showPhotoLabel.setIcon(icon);
            //}catch(IOException io) {
            //}

        info.addTab("Info", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(660, 851));

        serviceRecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Mileage", "Description", "Cost", "Company"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(serviceRecordTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );

        info.addTab("ServiceRecord", jPanel2);

        javax.swing.GroupLayout card2Layout = new javax.swing.GroupLayout(card2);
        card2.setLayout(card2Layout);
        card2Layout.setHorizontalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
            .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        card2Layout.setVerticalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(card2Layout.createSequentialGroup()
                    .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 220, Short.MAX_VALUE)))
        );

        info.getAccessibleContext().setAccessibleName("info");

        cardPanel.add(card2, "card2");

        getContentPane().add(cardPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void getData(Car data) {
        data.setBrand(brandTextField.getText());
        data.setModel(modelTextField.getText());
        data.setYear(yearTextField.getText());
        data.setColor(colorTextField.getText());
        data.setEngineNo(engineNoTextField.getText());
        data.setLicensePlates(licensePlatesTextField.getText());
        data.setSeatsNumber(Integer.parseInt(seatsNumberTextField.getText()));
        data.setWarrantyYear(warrantyYearTextField.getText());
        data.setPhoto(photoTextField.getText());
        data.setOwnerAddress(addressTextField.getText());
        data.setOwnerDriverLicense(driverLicenseTextField.getText());
        data.setOwnerTelephoneNumber(telephoneNumberTextField.getText());
        data.setOwnerName(nameTextField.getText());
        data.setOwnerEmail(emailAddressesTextField.getText());
        data.setOwnerSocialSecurityNumber(Integer.parseInt(socialSecurityNumberTextField.getText()));
        data.setServiceRecord(list);
    }
    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed
    public void setServiceRecord() {
        System.out.println(car.getServiceRecord());
    }

    public void setData(Car data) {
        brandTextField1.setText(data.getBrand());
        modelTextField1.setText(data.getModel());
        yearTextField1.setText(data.getYear());
        colorTextField1.setText(data.getColor());
        engineNoTextField1.setText(data.getEngineNo());
        seatsNumberTextField1.setText(String.valueOf(data.getSeatsNumber()));
        licensePlatesTextField1.setText(data.getLicensePlates());
        warrantyYearTextField1.setText(data.getWarrantyYear());
        javax.swing.ImageIcon icon;
        try {
            ShowImage si = new ShowImage();
            icon = si.getImage(car.getPhoto());
            showPhotoLabel.setIcon(icon);
        } catch (IOException io) {
            System.out.println(io);
        }
        nameTextField1.setText(data.getOwnerName());
        telephoneNumberTextField1.setText(data.getOwnerTelephoneNumber());
        driverLicenseTextField1.setText(data.getOwnerDriverLicense());
        emailAddressesTextField1.setText(data.getOwnerEmail());
        socialSecurityNumberTextField1.setText(String.valueOf(data.getOwnerSocialSecurityNumber()));
        addressTextField1.setText(data.getOwnerAddress());
    }

    public boolean validateServiceRecord() {

        if (dateTextField.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Date cannot be null", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        Verifier iv = new Verifier();
        Component[] notEmptyComponents = {
            mileageLabel, companyLabel, costLabel
        };
        for (int i = 0; i < notEmptyComponents.length; i++) {
            JLabel label = (JLabel) notEmptyComponents[i];
            JTextField field = (JTextField) label.getLabelFor();
            if (!iv.verify(field)) {
                String str = label.getText();
                JOptionPane.showMessageDialog(null, str.substring(0, str.length()) + " cannot be null", "Warning", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
        Component[] numberComponents = {
            mileageLabel, costLabel
        }; // these fields should be number
        for (int i = 0; i < numberComponents.length; i++) {
            JLabel label = (JLabel) numberComponents[i];
            JTextField field = (JTextField) label.getLabelFor();
            if (!iv.verifyNumber(field)) {
                String str = label.getText();
                JOptionPane.showMessageDialog(null, str.substring(0, str.length()) + " should be number", "Warning", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
//        System.out.println(dateTextField.getDate());
        return true;
    }

    public boolean validateData() {
        Verifier iv = new Verifier();
        Component[] notEmptyComponents = {
            brandLabel, modelLabel, yearLabel, colorLabel, engineNoLabel, seatsNumberLabel, licensePlatesLabel, warrantyYearLabel, photoLabel,
            nameLabel, telephoneNumberLabel, driverLicenseLabel, emailAddressesLabel, socialSecurityNumberLabel, addressLabel
        };
        for (int i = 0; i < notEmptyComponents.length; i++) {
            JLabel label = (JLabel) notEmptyComponents[i];
            JTextField field = (JTextField) label.getLabelFor();
            if (!iv.verify(field)) {
                String str = label.getText();
                JOptionPane.showMessageDialog(null, str.substring(0, str.length()) + " cannot be null", "Warning", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
        Component[] numberComponents = {
            yearLabel, warrantyYearLabel, seatsNumberLabel, telephoneNumberLabel, socialSecurityNumberLabel
        }; // these fields should be number
        for (int i = 0; i < numberComponents.length; i++) {
            JLabel label = (JLabel) numberComponents[i];
            JTextField field = (JTextField) label.getLabelFor();
            if (!iv.verifyNumber(field)) {
                String str = label.getText();
                JOptionPane.showMessageDialog(null, str.substring(0, str.length()) + " should be number", "Warning", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
        if (socialSecurityNumberTextField.getText().length() != 9) {
            JOptionPane.showMessageDialog(null, "Social Security Number should be 9 digit number", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (yearTextField.getText().length() != 4) {
            JOptionPane.showMessageDialog(null, "Year should be 4 digit number", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (warrantyYearTextField.getText().length() != 4) {
            JOptionPane.showMessageDialog(null, "Warranty year should be 9 digit number", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        JLabel emailComponent = emailAddressesLabel; // this field should match email regex
        JTextField field = (JTextField) emailComponent.getLabelFor();
        if (!iv.verifyEmail(field)) {
            JOptionPane.showMessageDialog(null, "email format is incorrect", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        if (validateData()) {
            java.awt.CardLayout cardLayout = (java.awt.CardLayout) cardPanel.getLayout();
            getData(car);
            setData(car);
            cardLayout.show(cardPanel, "card2");
            DefaultTableModel model = (DefaultTableModel) serviceRecordTable.getModel();
            Gson g = new Gson();
            for (int i = 0; i < car.getServiceRecord().size(); i++) {
                String json = g.toJson(list.get(i));
                System.out.println(json);
                Map row = g.fromJson(json, Map.class);
                Collection<Object> list = row.values();
                Object[] record = list.toArray();
                model.addRow(record);
            }
    }//GEN-LAST:event_nextButtonActionPerformed
    }
    private void brandTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FileDialog fd = new FileDialog();
        fd.showFileOpenDialog(cardPanel, photoTextField);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void driverLicenseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverLicenseTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverLicenseTextFieldActionPerformed

    private void nameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextField1ActionPerformed

    private void driverLicenseTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverLicenseTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverLicenseTextField1ActionPerformed

    private void brandTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandTextField1ActionPerformed

    private void engineNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engineNoTextFieldActionPerformed

    private void seatsNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatsNumberTextFieldActionPerformed

    private void telephoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneNumberTextFieldActionPerformed

    private void socialSecurityNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialSecurityNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_socialSecurityNumberTextFieldActionPerformed

    private void costTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costTextFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        enableServiceRecordFields();
        sr = new ServiceRecord();

    }//GEN-LAST:event_addButtonActionPerformed
    public static boolean isNumeric(String str) {
        String bigStr;
        try {
            bigStr = new BigDecimal(str).toString();
        } catch (Exception e) {
            return false;//异常 说明包含非数字。
        }
        return true;
    }
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:

        if (validateServiceRecord()) {
            sr.setDate(dateFormat.format(dateTextField.getDate()));
            sr.setCompany(companyTextField.getText());
            sr.setCost(Float.parseFloat(costTextField.getText()));
            sr.setDescription(descriptionTextArea.getText());
            sr.setMileage(Float.parseFloat(mileageTextField.getText()));
            list.add(sr);
            disableServiceRecordFields();
            clearServiceRecordFields();
            showCountLabel.setText("Added service record count: " + String.valueOf(++added));
        }
    }//GEN-LAST:event_saveButtonActionPerformed
    public void enableServiceRecordFields() {
        dateTextField.setEnabled(true);
//        dateTextField.setEditable(true);
        mileageTextField.setEditable(true);
        companyTextField.setEditable(true);
        costTextField.setEditable(true);
        descriptionTextArea.setEditable(true);
    }

    public void clearServiceRecordFields() {
        dateTextField.setDate(null);
        mileageTextField.setText("");
        companyTextField.setText("");
        costTextField.setText("");
        descriptionTextArea.setText("");
    }

    public void disableServiceRecordFields() {
        dateTextField.setEnabled(false);
        mileageTextField.setEditable(false);
        companyTextField.setEditable(false);
        costTextField.setEditable(false);
        descriptionTextArea.setEditable(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new container().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateLabel;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabel1;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField addressTextField1;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JLabel brandLabel1;
    private javax.swing.JTextField brandTextField;
    private javax.swing.JTextField brandTextField1;
    private info5100.Beans.Car car;
    private javax.swing.JPanel card1;
    private javax.swing.JPanel card2;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JLabel colorLabel1;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JTextField colorTextField1;
    private javax.swing.JLabel companyLabel;
    private javax.swing.JTextField companyTextField;
    private javax.swing.JLabel costLabel;
    private javax.swing.JTextField costTextField;
    private com.toedter.calendar.JDateChooser dateTextField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JScrollPane descriptionTextarea;
    private javax.swing.JLabel driverLicenseLabel;
    private javax.swing.JLabel driverLicenseLabel1;
    private javax.swing.JTextField driverLicenseTextField;
    private javax.swing.JTextField driverLicenseTextField1;
    private javax.swing.JLabel emailAddressesLabel;
    private javax.swing.JLabel emailAddressesLabel1;
    private javax.swing.JTextField emailAddressesTextField;
    private javax.swing.JTextField emailAddressesTextField1;
    private javax.swing.JLabel engineNoLabel;
    private javax.swing.JLabel engineNoLabel1;
    private javax.swing.JTextField engineNoTextField;
    private javax.swing.JTextField engineNoTextField1;
    private javax.swing.JTabbedPane info;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel licensePlateLabel1;
    private javax.swing.JLabel licensePlatesLabel;
    private javax.swing.JTextField licensePlatesTextField;
    private javax.swing.JTextField licensePlatesTextField1;
    private javax.swing.JLabel mileageLabel;
    private javax.swing.JTextField mileageTextField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JLabel modelLabel1;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JTextField modelTextField1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField nameTextField1;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JLabel photoLabel1;
    private javax.swing.JTextField photoTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel seatsNumberLabel;
    private javax.swing.JLabel seatsNumberLabel1;
    private javax.swing.JTextField seatsNumberTextField;
    private javax.swing.JTextField seatsNumberTextField1;
    private javax.swing.JTable serviceRecordTable;
    private javax.swing.JLabel showCountLabel;
    private javax.swing.JLabel showPhotoLabel;
    private javax.swing.JLabel socialSecurityNumberLabel;
    private javax.swing.JLabel socialSecurityNumberLabel1;
    private javax.swing.JTextField socialSecurityNumberTextField;
    private javax.swing.JTextField socialSecurityNumberTextField1;
    private javax.swing.JLabel telephoneNumberLabel;
    private javax.swing.JLabel telephoneNumberLabel1;
    private javax.swing.JTextField telephoneNumberTextField;
    private javax.swing.JTextField telephoneNumberTextField1;
    private javax.swing.JLabel warrantyLabel1;
    private javax.swing.JLabel warrantyYearLabel;
    private javax.swing.JTextField warrantyYearTextField;
    private javax.swing.JTextField warrantyYearTextField1;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JLabel yearLabel1;
    private javax.swing.JTextField yearTextField;
    private javax.swing.JTextField yearTextField1;
    // End of variables declaration//GEN-END:variables
}
